[package]
name = "observability"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
